export const REQUESTED_DASHBOARD = "REQUESTED_DASHBOARD";
export const REQUESTED_DASHBOARD_SUCCEEDED = "REQUESTED_DASHBOARD_SUCCEEDED";
export const REQUESTED_DASHBOARD_FAILED = "REQUESTED_DASHBOARD_FAILED";
export const FETCHED_DASHBOARD = "FETCHED_DASHBOARD";
export const FETCHED_LOCATIONS = "FETCHED_LOCATIONS";
export const REQUESTED_LOCATIONS_SUCCEEDED = "REQUESTED_LOCATIONS_SUCCEEDED";
