export const REQUESTED_POST_REPLY = "REQUESTED_POST_REPLY";
export const REQUESTED_POST_REPLY_SUCCEEDED = "REQUESTED_POST_REPLY_SUCCEEDED";
export const REQUESTED_POST_REPLY_FAILED = "REQUESTED_POST_REPLY_FAILED";
export const FETCHED_POST_REPLY = "FETCHED_POST_REPLY";