export const COMMENT_ON_POST = "COMMENT_ON_POST";
export const REQUESTED_COMMENT_ON_POST = "REQUESTED_COMMENT_ON_POST";
export const REQUESTED_COMMENT_ON_POST_SUCCEEDED =
  "REQUESTED_COMMENT_ON_POST_SUCCEEDED";
export const REQUESTED_COMMENT_ON_POST_FAILED =
  "REQUESTED_COMMENT_ON_POST_FAILED";

// comments
export const FETCH_POST_COMMENTS = "FETCH_POST_COMMENTS";
export const REQUESTED_POST_COMMENTS = "REQUESTED_POST_COMMENTS";
export const REQUESTED_POST_COMMENTS_SUCCEEDED =
  "REQUESTED_POST_COMMENTS_SUCCEEDED";
export const REQUESTED_POST_COMMENTS_FAILED = "REQUESTED_POST_COMMENTS_FAILED";
