export const REQUESTED_SCHEDULE = "REQUESTED_SCHEDULE";
export const REQUESTED_SCHEDULE_SUCCEEDED = "REQUESTED_SCHEDULE_SUCCEEDED";
export const REQUESTED_SCHEDULE_FAILED = "REQUESTED_SCHEDULE_FAILED";
export const FETCHED_SCHEDULE = "FETCHED_SCHEDULE";

export const REQUESTED_DEPARTMENTS = "REQUESTED_DEPARTMENTS";
export const REQUESTED_DEPARTMENTS_SUCCEEDED =
  "REQUESTED_DEPARTMENTS_SUCCEEDED";
export const REQUESTED_DEPARTMENTS_FAILED = "REQUESTED_DEPARTMENTS_FAILED";
export const FETCHED_DEPARTMENTS = "FETCHED_DEPARTMENTS";

export const REQUESTED_JOBS = "REQUESTED_JOBS";
export const REQUESTED_JOBS_SUCCEEDED = "REQUESTED_JOBS_SUCCEEDED";
export const REQUESTED_JOBS_FAILED = "REQUESTED_JOBS_FAILED";
export const FETCHED_JOBS = "FETCHED_JOBS";
