export const REQUESTED_SCHEDULE = "REQUESTED_SCHEDULE";
export const REQUESTED_SCHEDULE_SUCCEEDED = "REQUESTED_SCHEDULE_SUCCEEDED";
export const REQUESTED_SCHEDULE_FAILED = "REQUESTED_SCHEDULE_FAILED";
export const FETCHED_SCHEDULE = "FETCHED_SCHEDULE";