export const REQUESTED_DAY_SCHEDULES = "REQUESTED_SCHEDULES";
export const REQUESTED_DAY_SCHEDULES_SUCCEEDED =
  "REQUESTED_SCHEDULES_SUCCEEDED";
export const REQUESTED_DAY_SCHEDULES_FAILED = "REQUESTED_SCHEDULE_FAILED";
export const REQUEST_DAY_SCHEDULES = "REQUEST_DAY_SCHEDULES";
