export const REQUESTED_MESSAGE_DETAILS = "REQUESTED_MESSAGE_DETAILS";
export const REQUESTED_MESSAGE_DETAILS_SUCCEEDED = "REQUESTED_MESSAGE_DETAILS_SUCCEEDED";
export const REQUESTED_MESSAGE_DETAILS_FAILED = "REQUESTED_MESSAGE_DETAILS_FAILED";
export const FETCHED_MESSAGE_DETAILS = "FETCHED_MESSAGE_DETAILS";