export const REQUESTED_CHAT = "REQUESTED_CHAT";
export const REQUESTED_CHAT_SUCCEEDED = "REQUESTED_CHAT_SUCCEEDED";
export const REQUESTED_CHAT_FAILED = "REQUESTED_CHAT_FAILED";
export const FETCHED_CHAT = "FETCHED_CHAT";
