export const REQUESTED_NEW_POST = "REQUESTED_NEW_POST";
export const REQUESTED_NEW_POST_SUCCEEDED = "REQUESTED_NEW_POST_SUCCEEDED";
export const REQUESTED_NEW_POST_FAILED = "REQUESTED_NEW_POST_FAILED";
export const CREATE_NEW_POST = "CREATE_NEW_POST";